name: 'Terraform'

on:
  workflow_dispatch:
  
  push:
    branches: 
    - main

jobs:
    terraform-apply:
      name: "Terraform apply job"
      runs-on: ubuntu-latest
      
      steps:
      - name : Checkout
        uses : actions/checkout@v2
      
      - name : Setup Terraform
        uses :  hashicorp/setup-terraform@v1

      - name : Get GCP service account from github secrets
        run  : 'echo "$GCP_KEY" > credentials.json'
        env  :
           GCP_KEY : ${{secrets.GCP_key}}
      
      - name  : Terraform init
        run   : terraform init -reconfigure -backend-config=gcs_terraform_config
      
      - name  : Terraform apply
        run : terraform apply -input = false -auto-approve

